title: Shiye Su
description: "AI Research @ Stanford CS"
url: "https://ssu53.github.io"
baseurl: ""

# Author
author:
  name: "Shiye Su"
  email: "shiye@stanford.edu"
  twitter: "shiye_su"

# SEO
twitter:
  username: shiye_su

# Social
social:
  name: Shiye Su
  links:
    - https://twitter.com/shiye_su
    - https://github.com/ssu53
    - https://www.linkedin.com/in/shiye-su/
    - https://scholar.google.com/citations?user=lLew4RwAAAAJ

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
